### PR TITLE
Enhance `DataProcessor` Class for Error Handling, Efficiency, and Logging Improvements

### PR DESCRIPTION
**Pull request by Mefisto04**
This pull request aims to enhance the `DataProcessor` class by implementing the following changes to improve error handling, optimize efficiency, and enhance logging capabilities.

### Changes Made:
1. **Error Handling Improvements:**  
   - Added `try-except` blocks in file reading, URL processing, and directory processing functions to handle exceptions gracefully.
   - Used the logger to log error messages for better traceability and debugging.

2. **Optimized File and Directory Handling:**  
   - Simplified path operations using Python's built-in utilities such as `os.path` and `Path`.
   - Ensured robust file handling with directory creation checks and removal of temporary files when appropriate.

3. **Improved Multiprocessing Usage:**  
   - Refined the usage of `multiprocessing.Pool` to minimize overhead.
   - Enhanced progress tracking with the `tqdm` library for better user feedback during processing.

4. **Logging Enhancements:**  
   - Added detailed logging at key steps, including file reading, content processing, and error conditions, to provide insights into the data processing workflow.
   - Included log messages to indicate the completion of each processing step, with additional context for directory and URL processing.

These changes enhance the reliability and performance of the `DataProcessor` class.

### CODE REVIEW

**Comment by Mefisto04** [comment]
hey @aravind10x, please review these changes.

**Comment by aravind10x** [comment]
LGTM. @ashwinzyx any thoughts? I'll let you approve it since you authored this one.

**Comment by Mefisto04** [comment]
any update @aravind10x ?

**Review by ashwinzyx — APPROVED** [review]
LGTM

**Pull request merged**
